// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Booking struct {
	BookingCode string `json:"booking_code"`
	BookingDate string `json:"booking_date"`
}

type ChangeCustomerPassword struct {
	ID          string `json:"id"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type CreateNewCustomer struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	DateOfBith string `json:"date_of_bith"`
	Address    string `json:"address"`
	Email      string `json:"email"`
	Password   string `json:"password"`
}

type CreateNewFlight struct {
	ID          string `json:"id"`
	From        string `json:"from"`
	To          string `json:"to"`
	DepartDate  string `json:"depart_date"`
	DepartTime  string `json:"depart_time"`
	Status      string `json:"status"`
	Slot        string `json:"slot"`
	FlightPlane string `json:"flight_plane"`
}

type Customer struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	DateOfBith string `json:"date_of_bith"`
	Address    string `json:"address"`
	Email      string `json:"email"`
}

type Empty struct {
	Text string `json:"text"`
}

type Flight struct {
	ID          string `json:"id"`
	From        string `json:"from"`
	To          string `json:"to"`
	DepartDate  string `json:"depart_date"`
	DepartTime  string `json:"depart_time"`
	Status      string `json:"status"`
	Slot        string `json:"slot"`
	FlightPlane string `json:"flight_plane"`
}

type UpdateCustomer struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	DateOfBith string `json:"date_of_bith"`
	Address    string `json:"address"`
	Email      string `json:"email"`
}

type ViewCustomerBookingHistories struct {
	ID string `json:"id"`
}
